#!/bin/bash

HOME_DIR="/home/vagrant"

# Shared comes from shell provisioner in VagrantFile
DOWNLOAD_DIR="/vagrant/downloads"
CATALINA_HOME="/usr/share/tomcat"
DJATOKA_HOME="/usr/local/djatoka"

FEDORA_HOME="/usr/local/fedora"

#FFMPEG_VERSION=1.1.4

FITS_HOME="/usr/local/fits"
FITS_VERSION="1.1.0"

SOLR_HOME="/usr/local/solr"
SOLR_VERSION="4.2.0"

DRUPAL_HOME="/vhosts/digital/web/collections"

CANTALOUPE_HOME="/usr/local/cantaloupe"
CANTALOUPE_LOGS="/var/log/cantaloupe"
CANTALOUPE_CACHE="/var/cache/cantaloupe"
CANTALOUPE_VERSION=3.4.4
